In [1]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [2]:
X=[[1,2], [5,4],[3,4], [5,6]]
y=[1,0,1,0]  #y now has 4 values matching X's samples
rfe = RFE(estimator=LogisticRegression(), n_features_to_select=1)
X_new = rfe.fit_transform(X, y)
print (X_new)

[[1]
 [5]
 [3]
 [5]]


In [3]:

from sklearn.feature_selection import VarianceThreshold
import numpy as np
X = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
selector = VarianceThreshold(threshold=0)
try:
    X_new = selector.fit_transform(X)
    print(X_new.shape)
except ValueError as e:
    print(f"Error: {e}")
    print("All features have zero variance. Consider adjusting the threshold.")

Error: No feature in X meets the variance threshold 0.00000
All features have zero variance. Consider adjusting the threshold.


In [4]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
#define vectors 
vector_A = np.array([[5, 0, 3]])
vector_B = np.array([[0, 0, 0]])
#calculate cosine similarity
similarity = cosine_similarity(vector_A, vector_B)
print("Cosine Similarity:", similarity[0][0])


Cosine Similarity: 0.0


In [5]:

from sklearn.feature_selection import SelectFromModel
from sklearn.tree import DecisionTreeClassifier

X = [[1, 2], [3, 4], [5, 6]]
y = [1, 0, 1]
selector = SelectFromModel(DecisionTreeClassifier(), threshold="mean")
X_new = selector.fit_transform(X, y)
print("Selected Features Shape:", X_new.shape)
print("Transformed X:\n", X_new)


Selected Features Shape: (3, 1)
Transformed X:
 [[1]
 [3]
 [5]]


In [6]:
import pandas as pd
data = pd.DataFrame({
    'user': ['A', 'B', 'A'],
    'item': ['I1', 'I2', 'I2'],
    'rating': [5, 4, 3]
})
pivot = data.pivot(index='user', columns='item', values='rating')
print(pivot)
                                                                                                                                                                            

item   I1   I2
user          
A     5.0  3.0
B     NaN  4.0


In [7]:
#6.
from sklearn.decomposition import PCA
import numpy as np

X = np.array([[1, 2], [3, 4]])
pca = PCA(n_components=1)
X_new = pca.fit_transform(X)
print(X_new)


[[-1.41421356]
 [ 1.41421356]]


In [8]:
#7.
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
ratings = pd.DataFrame({
    'User1': [5, 0, 3],
    'User2': [0, 4, 0],
    'User3': [1, 2, 0]
})
sim = cosine_similarity(ratings.T)
print(sim)


[[1.         0.         0.38348249]
 [0.         1.         0.89442719]
 [0.38348249 0.89442719 1.        ]]


In [9]:
#8.
import numpy as np

user_vec = np.array([1, 2])
item_vec = np.array([0.5, 1.0])
score = np.dot(user_vec, item_vec)
print("Predicted Score:", score)


Predicted Score: 2.5


In [10]:
#9.
from sklearn.neighbors import NearestNeighbors
import numpy as np

X = np.array([[1, 0, 1], [0, 1, 0], [1, 1, 1]])
model = NearestNeighbors()
model.fit(X)
distances, indices = model.kneighbors([X[0]], n_neighbors=2)
print(indices)


[[0 2]]


In [11]:
#10.
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

a = np.array([[1, 0, 1]])
b = np.array([[0, 1, 1]])

sim = cosine_similarity(a, b)
print("Similarity:", sim[0][0])

Similarity: 0.4999999999999999
